trigger:
  branches:
   include:
     - main
  paths:
    include:
      - app
      - core
      - ui
      - setup
      - tools

jobs:
- job: FlowFM_Inspector_Core
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      Python39:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - task: CmdLine@2
    inputs:
      script: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      workingDirectory: '$(Build.Repository.LocalPath)\core'
    displayName: 'Install dependencies'

  - task: CmdLine@2
    inputs:
      script: |
        poetry run python -m PyInstaller .\flowfm_inspector\main.py -y --clean --hidden-import cftime -n core
      workingDirectory: '$(Build.Repository.LocalPath)\core'
    displayName: 'Package flowfm_inspector with PyInstaller'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/core/dist/'
      Contents: 'core/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy PyInstaller results'

  - publish: '$(Build.ArtifactStagingDirectory)/core'
    displayName: 'Publish package'
    artifact: core

- job: FlowFM_Inspector_App
  pool:
    vmImage: windows-2022

  variables:
    solution: '**/app/FlowFM-Inspector.sln'
    build_configuration: 'Release'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'NuGet - Install'
    inputs:
      versionSpec: 6.x
  
  - task: NuGetCommand@2
    displayName: 'NuGet - Restore Packages'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
  
  - task: VSBuild@1
    displayName: 'Build FlowFM-Installer app'
    inputs:
      solution: '$(solution)'
      configuration: '$(build_configuration)'
      msbuildArchitecture: 'x64'
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/app/FlowFM-Inspector/bin/$(build_configuration)/net6.0-windows/win10-x64/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy MSBuild results'
  
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish package'
    artifact: app

- job: FlowFM_Inspector_UI
  pool:
    vmImage: windows-2022

  variables:
    working_directory: '$(Build.Repository.LocalPath)\ui'

  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '16.x'
  
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'install'
      workingDir: '$(working_directory)'

  - task: CmdLine@2
    displayName: 'Install gatsby-cli'
    inputs:
      script: 'npm i -g gatsby-cli'
      workingDirectory: '$(working_directory)'

  - task: CmdLine@2
    displayName: 'Build gatsby ui'
    inputs:
      script: 'gatsby build --prefix-paths'
      workingDirectory: '$(working_directory)'
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(working_directory)/public/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Gatsby Build results'
  
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish package'
    artifact: ui

- job: FlowFM_Inspector_Installer
  pool:
    vmImage: windows-2022

  strategy:
    matrix:
      Python39:
        python.version: '3.9'

  variables:
    working_directory: '$(Build.Repository.LocalPath)\build'
    setup_directory: '$(Build.Repository.LocalPath)\setup\FlowFM-Inspector'
    solution: '**/setup/FlowFM-Inspector-setup.sln'
    build_configuration: 'Release'

  dependsOn:
    - FlowFM_Inspector_Core
    - FlowFM_Inspector_UI
    - FlowFM_Inspector_App

  steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      artifactName: 'app'
      downloadType: 'single'
      downloadPath: '$(working_directory)'

  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      artifactName: 'ui'
      downloadType: 'single'
      downloadPath: '$(working_directory)\ui'

  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      artifactName: 'core'
      downloadType: 'single'
      downloadPath: '$(working_directory)\core'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - task: CmdLine@2
    inputs:
      script: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      workingDirectory: '$(Build.Repository.LocalPath)\tools'
    displayName: 'Install Python dependencies'

  - task: CmdLine@2
    inputs:
      script: |
        poetry run python .\tools\main.py generate-directories-fragment "$(working_directory)" --target-directory "$(setup_directory)" --excluded-directories "runtimes"
        poetry run python .\tools\main.py generate-component-fragment "$(working_directory)" "core" --included-paths "core" --target-directory "$(setup_directory)\Components"
        poetry run python .\tools\main.py generate-component-fragment "$(working_directory)" "ui" --included-paths "ui" --target-directory "$(setup_directory)\Components"
        poetry run python .\tools\main.py generate-component-fragment "$(working_directory)" "app" --included-paths "." --excluded-paths "ui" --excluded-paths "core" --excluded-paths "runtimes" --target-directory "$(setup_directory)\Components" --additional-component-groups-refs "app..exutecutable" --excluded-paths "FlowFM-Inspector.exe"                                                                                                                                            
      workingDirectory: '$(Build.Repository.LocalPath)\tools'
    displayName: 'Generate the required fragments'

  - task: VSBuild@1
    displayName: 'Build - Executables'
    inputs:
      solution: '$(solution)'
      configuration: '$(build_configuration)'
      platform: 'x64'
      msbuildArchitecture: 'x64'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(setup_directory)\bin'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy MSI'
  
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish msi'
    artifact: msi
